## from pr
# CHROM_COL = "Chromosome"
# START_COL = "Start"
# END_COL = "End"
# STRAND_COL = "Strand"
##FEAT_COL = "Feature"


PR_INDEX_COL = "__pr_ix__"
ORISTART_COL = "__oriStart__"
ORIEND_COL = "__oriEnd__"
SHRTHRES_COL = "__shrink_threshold__"
ADJSTART_COL = "__Start_adj__"
ADJEND_COL = "__End_adj__"
CUM_DELTA_COL = "__cumdelta__"
DELTA_COL = "__delta__"
COLOR_TAG_COL = "__color_tag__"
COLOR_INFO = "__color_col__"
BORDER_COLOR_COL = "__exon_border__"
OUTLINE_TAG_COL = "__outline_tag__"
COLOR_LEGEND_KIND_COL = "__color_legend_kind__"
OUTLINE_LEGEND_KIND_COL = "__outline_legend_kind__"
COLOR_LEGEND_TITLE_COL = "__color_legend_title__"
OUTLINE_LEGEND_TITLE_COL = "__outline_legend_title__"
EXON_IX_COL = "__exon_ix__"
TEXT_PAD_COL = "__text_pad__"
TEXT_LABEL_COL = "__text_label__"
TEXT_START_COL = "__text_start__"
TEXT_END_COL = "__text_end__"
TEXT_MID_COL = "__text_mid__"
TEXT_PAD_FRAC_COL = "__text_pad_frac__"
TEXT_PAD_Y_COL = "__text_pad_y__"
TEXT_HEIGHT_COL = "__text_height__"
THICK_COL = "__thickness_col__"
SHAPE_COL = "__shape_col__"
MARKER_SIZE_COL = "__marker_size_col__"

# Panel/region splitting (multi-window per chromosome)
PANEL_SEP = (
    "@"  # internal separator: synthetic chromosome key = f"{chrom}{PANEL_SEP}{ix}"
)
